### ISSUE TITLE
Panic with large numbers of subscribers and producers !

### ISSUE THREAD

**Issue by ihsenCh** [fhmq/hmq#24]
I wrote a client program based on paho in golang. It starts multiple publishers & subcribers using goroutines.
When the broker is running on the server, this panic appears once I increase pub/sub numbers ( once we reach a few thousands the error appears fairly frequently )
At first, the program works and some messages are correctly received by the subscribers. But then, the broker throws this panic in the middle of the program.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x665daa]

goroutine 10903 [running]:
github.com/eclipse/paho.mqtt.golang/packets.(*PublishPacket).Write(0xc4229880c0, 0x0, 0x0, 0x0, 0x0)
       /home/ihsen/Documents/Hmq/src/github.com/eclipse/paho.mqtt.golang/packets/publish.go:39 +0x25a
github.com/fhmq/hmq/broker.(*client).WriterPacket(0xc4213045a0, 0x7781c0, 0xc4229880c0, 0xc423bebd00, 0x2)
       /home/ihsen/Documents/Hmq/src/github.com/fhmq/hmq/broker/client.go:535 +0xb2
github.com/fhmq/hmq/broker.(*client).ProcessPublishMessage(0xc425ba90e0, 0xc4229880c0)
       /home/ihsen/Documents/Hmq/src/github.com/fhmq/hmq/broker/client.go:250 +0x124
github.com/fhmq/hmq/broker.(*client).ProcessPublish(0xc425ba90e0, 0xc4229880c0)
       /home/ihsen/Documents/Hmq/src/github.com/fhmq/hmq/broker/client.go:199 +0x8a1
github.com/fhmq/hmq/broker.ProcessMessage(0xc421af20c0)
       /home/ihsen/Documents/Hmq/src/github.com/fhmq/hmq/broker/client.go:158 +0x574
github.com/fhmq/hmq/broker.(*Broker).StartDispatcher.func1.1()
       /home/ihsen/Documents/Hmq/src/github.com/fhmq/hmq/broker/broker.go:102 +0x2a
github.com/fhmq/hmq/pool.startWorker.func1(0xc4201cc000, 0xc42009e3c0)
       /home/ihsen/Documents/Hmq/src/github.com/fhmq/hmq/pool/pool.go:160 +0x68
created by github.com/fhmq/hmq/pool.startWorker
       /home/ihsen/Documents/Hmq/src/github.com/fhmq/hmq/pool/pool.go:145 +0x49
	   
Not long before the crash, we observe some broken pipe errors, but we do not know if the errors are connected with the crash.
{"level":"error","ts":1523275251.1890993,"logger":"hmq.Broker","caller":"broker/client.go:252","msg":"process message for psub error,  ","error":"write tcp 127.0.0.1:1883->127.0.0.1:40269: write: broken pipe","ClientID":"client107"}

Any idea of what is wrong with this ?

**Comment by lukaizhi** [comment]
我也遇到了这个问题

**Comment by chowyu08** [comment]
I have fixed the write logic to keep from this issue.

**Comment by ihsenCh** [comment]
Yes It seems fine now. 
Regarding wildcard, I know that hmq doesn't support ( untill now) topic wildcard, but I tried to test it and I get similar panic. I think it is better to explicitly describe "no wildcard supporting" error.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x68442e]

goroutine 7 [running]:
github.com/fhmq/hmq/broker.addNodeToResults(...)
        /home/ihsen/Documents/Hmq/src/github.com/fhmq/hmq/broker/sublist.go:286
github.com/fhmq/hmq/broker.matchLevel(0xc42000e028, 0xc42000c240, 0x2, 0x2, 0xc4201b4210)
        /home/ihsen/Documents/Hmq/src/github.com/fhmq/hmq/broker/sublist.go:280 +0xa7e
github.com/fhmq/hmq/broker.(*Sublist).Match(0xc42007cfc0, 0xc4200141e0, 0xa, 0x0)
        /home/ihsen/Documents/Hmq/src/github.com/fhmq/hmq/broker/sublist.go:233 +0x36d
github.com/fhmq/hmq/broker.(*client).ProcessPublishMessage(0xc4201c60f0, 0xc42005c2c0)
        /home/ihsen/Documents/Hmq/src/github.com/fhmq/hmq/broker/client.go:244 +0x9c
github.com/fhmq/hmq/broker.(*client).ProcessPublish(0xc4201c60f0, 0xc42005c2c0)
        /home/ihsen/Documents/Hmq/src/github.com/fhmq/hmq/broker/client.go:206 +0x87c
github.com/fhmq/hmq/broker.ProcessMessage(0xc42000c220)
        /home/ihsen/Documents/Hmq/src/github.com/fhmq/hmq/broker/client.go:165 +0x574
github.com/fhmq/hmq/broker.(*Broker).SubmitWork.func1()
        /home/ihsen/Documents/Hmq/src/github.com/fhmq/hmq/broker/broker.go:101 +0x2a
github.com/fhmq/hmq/pool.startWorker.func1(0xc4201a2000, 0xc42009e3c0)
        /home/ihsen/Documents/Hmq/src/github.com/fhmq/hmq/pool/pool.go:172 +0x90
created by github.com/fhmq/hmq/pool.startWorker
        /home/ihsen/Documents/Hmq/src/github.com/fhmq/hmq/pool/pool.go:154 +0x49

**Comment by JaosnHsieh** [comment]
i also encountered this problem. during this panic period, the broker is slower to pub and sub messages, around 4 mins a few times in a day , did u find any reasons or workaround for this?

**Comment by lukaizhi** [comment]
I don't used it, Used other products 

发自我的iPhone
