### ISSUE TITLE
用一段时间后会自动挂掉。呕血，连续几次了。邮件又没人回。哎

### ISSUE THREAD

**Issue by svija** [fhmq/hmq#33]
用一段时间后会自动挂掉。呕血，连续几次了。邮件又没人回。哎

**Comment by svija** [comment]
2018-08-17 11:26:43,821  INFO --- MqttFX ClientModel             : messageArrived() with topic: /luatask/demo/rep/869300035511553
2018-08-17 11:26:43,822  INFO --- MqttFX ClientModel             : messageArrived() added: message #148 to topic '/luatask/demo/rep/869300035511553'
2018-08-17 11:26:43,833  INFO --- ReceivedMessagesController     : TopicsCollectorService: messageArrived: topic: /luatask/demo/rep/869300035511553
2018-08-17 11:26:51,868  INFO --- MqttFX ClientModel             : messageArrived() with topic: /luatask/demo/rep/869300035506744
2018-08-17 11:26:51,868  INFO --- MqttFX ClientModel             : messageArrived() added: message #149 to topic '/luatask/demo/rep/869300035506744'
2018-08-17 11:26:51,873  INFO --- ReceivedMessagesController     : TopicsCollectorService: messageArrived: topic: /luatask/demo/rep/869300035506744
2018-08-17 11:27:00,688  INFO --- MqttFX ClientModel             : messageArrived() with topic: /luatask/demo/rep/869300035506744
2018-08-17 11:27:00,689  INFO --- MqttFX ClientModel             : messageArrived() added: message #150 to topic '/luatask/demo/rep/869300035506744'
2018-08-17 11:27:06,629  INFO --- MqttFX ClientModel             : Broker connection lost: Resetting client.
2018-08-17 11:27:06,635  INFO --- ScriptsController              : Clear console.
2018-08-17 11:27:06,636  INFO --- MqttFX ClientModel             : rebuildMessagesList()
2018-08-17 11:27:06,639  INFO --- MqttFX ClientModel             : rebuildMessagesList()
2018-08-17 11:27:06,642  INFO --- ScriptsController              : Clear console.
2018-08-17 11:27:46,638  INFO --- ReceivedMessagesController     : onSubscribeAllSelectedTopics()
2018-08-17 11:27:51,410  INFO --- BrokerConnectorController      : onConnect
2018-08-17 11:27:51,412  INFO --- ScriptsController              : Clear console.
2018-08-17 11:27:51,413  INFO --- MqttFX ClientModel             : MqttClient with ID 9ecff89534e3438781cd75ec8896aa05 assigned.
2018-08-17 11:27:52,545 ERROR --- MqttFX ClientModel             : Error when connecting
org.eclipse.paho.client.mqttv3.MqttException: Unable to connect to server
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:94) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[?:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_162]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[?:1.8.0_162]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[?:1.8.0_162]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_162]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_162]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_162]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_162]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_162]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_162]

**Comment by svija** [comment]
TOO MANY BUGS

**Comment by chowyu08** [comment]
> 用一段时间后会自动挂掉。呕血，连续几次了。邮件又没人回。哎
