### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference after i/o timeout

### ISSUE THREAD

**Issue by muXxer** [fhmq/hmq#96]
Hi hmq team!

thanks for this great piece of software!

Version:
`github.com/fhmq/hmq v0.0.0-20200624071425-481a61c520fe`

We often have a panic because of a nil pointer dereference after a client closed the connection.

```
Aug 25 18:57:05 bare04.aws.XYZ.de docker[333676]: {"level":"error","timestamp":"2020-08-25T18:57:05.487Z","logger":"broker","caller":"broker/client.go:143","msg":"read packet error: ","error":"read tcp xxx.xxx.xxx.xxx:1883->xxx.xxx.xxx.xxx:44970: i/o timeout","ClientID":"nmapNSJKJLFQRGOLJUAE"}
Aug 25 18:57:05 bare04.aws.XYZ.de docker[333676]: {"level":"error","timestamp":"2020-08-25T18:57:05.488Z","logger":"broker","caller":"broker/broker.go:616","msg":"write message error,  ","error":"write tcp xxx.xxx.xxx.xxx:1883->xxx.xxx.xxx.xxx:44970: use of closed network connection"}
Aug 25 18:57:05 bare04.aws.XYZ.de docker[333676]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 25 18:57:05 bare04.aws.XYZ.de docker[333676]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc79e25]
Aug 25 18:57:05 bare04.aws.XYZ.de docker[333676]: goroutine 2324 [running]:
Aug 25 18:57:05 bare04.aws.XYZ.de docker[333676]: github.com/eclipse/paho.mqtt.golang/packets.(*PublishPacket).Write(0xc00e75ca00, 0x0, 0x0, 0x0, 0x0)
Aug 25 18:57:05 bare04.aws.XYZ.de docker[333676]:         /go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.1-0.20200506085104-5ee50844ed64/packets/publish.go:34 +0x225
Aug 25 18:57:05 bare04.aws.XYZ.de docker[333676]: github.com/fhmq/hmq/broker.(*client).WriterPacket(0xc0000c8280, 0x2308ba0, 0xc00e75ca00, 0x8, 0x0)
Aug 25 18:57:05 bare04.aws.XYZ.de docker[333676]:         /go/pkg/mod/github.com/fhmq/hmq@v0.0.0-20200624071425-481a61c520fe/broker/client.go:678 +0xbc
Aug 25 18:57:05 bare04.aws.XYZ.de docker[333676]: github.com/fhmq/hmq/broker.(*Broker).PublishMessage(0xc004d94000, 0xc00e75ca00)
Aug 25 18:57:05 bare04.aws.XYZ.de docker[333676]:         /go/pkg/mod/github.com/fhmq/hmq@v0.0.0-20200624071425-481a61c520fe/broker/broker.go:614 +0x1c9
Aug 25 18:57:05 bare04.aws.XYZ.de docker[333676]: github.com/gohornet/hornet/plugins/mqtt.(*Broker).Send(0xc00075d390, 0x133669c, 0x3, 0xc020b5c050, 0x44, 0xc020b5c050, 0x44)
```

Are we doing something wrong here?
Do you need more logs?

Thank you very much!

**Comment by muXxer** [comment]
Thx!
